/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookATourRouteImport } from './routes/book-a-tour'
import { Route as BookAdminRouteImport } from './routes/book-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMailGoogleCallbackRouteImport } from './routes/api/mail/google/callback'
import { Route as ApiMailGoogleConnectRouteImport } from './routes/api/mail/google/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookATourRoute = BookATourRouteImport.update({
  id: '/book-a-tour',
  path: '/book-a-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAdminRoute = BookAdminRouteImport.update({
  id: '/book-admin',
  path: '/book-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailGoogleCallbackRoute = ApiMailGoogleCallbackRouteImport.update({
  id: '/api/mail/google/callback',
  path: '/api/mail/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailGoogleConnectRoute = ApiMailGoogleConnectRouteImport.update({
  id: '/api/mail/google/connect',
  path: '/api/mail/google/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book-a-tour': typeof BookATourRoute
  '/book-admin': typeof BookAdminRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/google/callback': typeof ApiMailGoogleCallbackRoute
  '/api/mail/google/connect': typeof ApiMailGoogleConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book-a-tour': typeof BookATourRoute
  '/book-admin': typeof BookAdminRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/google/callback': typeof ApiMailGoogleCallbackRoute
  '/api/mail/google/connect': typeof ApiMailGoogleConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book-a-tour': typeof BookATourRoute
  '/book-admin': typeof BookAdminRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mail/google/callback': typeof ApiMailGoogleCallbackRoute
  '/api/mail/google/connect': typeof ApiMailGoogleConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book-a-tour'
    | '/book-admin'
    | '/login'
    | '/reset-password'
    | '/api/auth/$'
    | '/api/mail/google/callback'
    | '/api/mail/google/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book-a-tour'
    | '/book-admin'
    | '/login'
    | '/reset-password'
    | '/api/auth/$'
    | '/api/mail/google/callback'
    | '/api/mail/google/connect'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book-a-tour'
    | '/book-admin'
    | '/login'
    | '/reset-password'
    | '/api/auth/$'
    | '/api/mail/google/callback'
    | '/api/mail/google/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookATourRoute: typeof BookATourRoute
  BookAdminRoute: typeof BookAdminRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMailGoogleCallbackRoute: typeof ApiMailGoogleCallbackRoute
  ApiMailGoogleConnectRoute: typeof ApiMailGoogleConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-tour': {
      id: '/book-a-tour'
      path: '/book-a-tour'
      fullPath: '/book-a-tour'
      preLoaderRoute: typeof BookATourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-admin': {
      id: '/book-admin'
      path: '/book-admin'
      fullPath: '/book-admin'
      preLoaderRoute: typeof BookAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/google/callback': {
      id: '/api/mail/google/callback'
      path: '/api/mail/google/callback'
      fullPath: '/api/mail/google/callback'
      preLoaderRoute: typeof ApiMailGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/google/connect': {
      id: '/api/mail/google/connect'
      path: '/api/mail/google/connect'
      fullPath: '/api/mail/google/connect'
      preLoaderRoute: typeof ApiMailGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookATourRoute: BookATourRoute,
  BookAdminRoute: BookAdminRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMailGoogleCallbackRoute: ApiMailGoogleCallbackRoute,
  ApiMailGoogleConnectRoute: ApiMailGoogleConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
